- name: "Create {{ swarmsible_swarmsible_hetzner_ansible_root_ssh_key_name }} ssh_key"
  hcloud_ssh_key:
    name: "{{ swarmsible_swarmsible_hetzner_ansible_root_ssh_key_name }}"
    public_key: "{{ lookup('ansible.builtin.file', swarmsible_hetzner_ansible_root_ssh_key) }}"
    state: present
    api_token: "{{ hcloud_token }}"
