- name: Create swarm-servers firewall
  hetzner.hcloud.hcloud_firewall:
    name: swarm-servers
    api_token: "{{ hcloud_token }}"
    rules:
      - direction: in
        protocol: tcp
        port: 22
        source_ips:
          - 0.0.0.0/0
          - ::/0
        description: allow ssh in
      - direction: in
        protocol: icmp
        source_ips:
          - 0.0.0.0/0
          - ::/0
        description: allow icmp in

      - direction: in
        protocol: tcp
        port: any
        source_ips:
          - 192.168.0.0/16
        description: allow all tcp traffic in private networks

      - direction: in
        protocol: udp
        port: any
        source_ips:
          - 192.168.0.0/16
        description: allow all udp traffic in private networks

      - direction: in
        protocol: esp
        source_ips:
          - 192.168.0.0/16
        description: allow all esp traffic in private networks
    state: present
  register: swarm_servers_firewall
