{
 "title": "Precision X - Systems Overview",
 "time": { "from": "2023-02-24T23:40:17.122Z", "to": "2023-02-28T08:19:14.399Z" },
 "panels": [
  { "title": "Bid Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "total rate bidding requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (rate(precx_bidding_requests[$__rate_interval]))",
     "legendFormat": "total rate bidding requests"
    }
   ]
  },
  {
   "title": "Chosen Creatives",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(creative_id) (precx_chosen_creatives)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tracking Overview",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (precx_events_stored{event_type=\"TRACKING#START\"})",
     "legendFormat": "Tracking Start"
    },
    {
     "expr": "sum(precx_events_stored{event_type=\"TRACKING#FIRST_QUARTILE\"})",
     "legendFormat": "Tracking First Quartile"
    },
    {
     "expr": "sum(precx_events_stored{event_type=\"TRACKING#MIDPOINT\"})",
     "legendFormat": "Tracking Midpoint"
    },
    {
     "expr": "sum(precx_events_stored{event_type=\"TRACKING#THIRD_QUARTILE\"})",
     "legendFormat": "Tracking Third Quartile"
    },
    {
     "expr": "sum(precx_events_stored{event_type=\"TRACKING#COMPLETE\"})",
     "legendFormat": "Tracking Complete"
    }
   ]
  },
  {
   "title": "Request/Response ratio",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 3, "x": 19, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(event_type) (precx_events_stored{event_type=~\"api-ad-stele-request|api-ad-stele-response\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[DRAFT]Rates: Fallback vs SSP vs VAST Ads vs CMS Ads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(precx_fallback_ads[$__rate_interval]))",
     "legendFormat": "Fallback Ads"
    },
    {
     "expr": "sum(rate(precx_ssp_ads[$__rate_interval])) OR on() vector(0)",
     "legendFormat": "SSP Ads"
    },
    {
     "expr": "sum(rate(precx_cms_ads[$__rate_interval])) OR on() vector(0)",
     "legendFormat": "CMS Ads"
    }
   ]
  }
 ]
}