{
 "title": "Hetzner",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Load Balancer Targets Health",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "hcloud_loadbalancer_targets_healthy{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hcloud_loadbalancer_targets_unhealthy{}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hcloud_loadbalancer_targets_unknown{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Balancer Connections per Second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "hcloud_loadbalancer_connections_per_second{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "hcloud_server_incoming_traffic_bytes{} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Outoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "hcloud_server_outgoing_traffic_bytes{} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}